"""
Django settings for diario_back_api project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
import dj_database_url
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', default='')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False  # Cambiado a False para producción

ALLOWED_HOSTS = ['api.diarioelgobierno.ar', 'localhost', '127.0.0.1']
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:    
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'diarioback'
]

# Session configuration
SESSION_TRUSTED = 'django.contrib.sessions.backends.db'
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # DEBE estar primero
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ========================================
# CONFIGURACIÓN CORS COMPLETAMENTE ABIERTA
# ¡PELIGROSO! SOLO PARA DEBUGGING
# ========================================

# Permite TODOS los orígenes - CUALQUIER SITIO WEB puede hacer peticiones
CORS_ALLOW_ALL_ORIGINS = True

# Permite credenciales (cookies, tokens JWT, headers de autorización)
CORS_ALLOW_CREDENTIALS = True

# Permite TODOS los headers
CORS_ALLOW_HEADERS = [
    '*',  # Esto permite cualquier header
]

# O específicamente todos estos headers comunes:
# CORS_ALLOW_HEADERS = [
#     'accept',
#     'accept-encoding',
#     'authorization',
#     'content-type',
#     'dnt',
#     'origin',
#     'user-agent',
#     'x-csrftoken',
#     'x-requested-with',
#     'access-control-allow-origin',
#     'x-forwarded-for',
#     'x-forwarded-proto',
#     'x-real-ip',
#     'cache-control',
#     'pragma',
#     'expires',
#     'if-modified-since',
#     'if-none-match',
# ]

# Permite TODOS los métodos HTTP
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
    'HEAD',
    'TRACE',
    'CONNECT',
]

# Permite preflight para todas las peticiones
CORS_PREFLIGHT_MAX_AGE = 86400

# Expone todos los headers en las respuestas
CORS_EXPOSE_HEADERS = ['*']

# Comentar o eliminar la configuración restrictiva anterior:
# CORS_ALLOWED_ORIGINS = [...]  # COMENTADO

# ========================================
# FIN CONFIGURACIÓN CORS ABIERTA
# ========================================

# CSRF Configuration - También más permisivo para evitar conflictos
CSRF_TRUSTED_ORIGINS = [
    'https://api.diarioelgobierno.ar',
    'https://diarioelgobierno.ar',
    'http://64.23.212.155',
    'https://*.diarioelgobierno.ar',  # Cualquier subdominio
    'http://*.diarioelgobierno.ar',   # HTTP también
]

# Deshabilitar algunas protecciones CSRF para debugging
# CSRF_COOKIE_SECURE = False  # Descomenta si tienes problemas con HTTPS
# CSRF_USE_SESSIONS = True    # Descomenta si tienes problemas con cookies

ROOT_URLCONF = 'diario_back_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'diario_back_api.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',        
        'NAME': 'projectone',
        'USER': 'projectoneuser',
        'PASSWORD': os.environ.get('DB_PASSWORD', default=''),
        'HOST': 'localhost',
        'PORT': ''
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
if not DEBUG:    
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',        
    ],
}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# JWT Configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
}

# Security Configuration - Más permisivo para debugging
SECURE_SSL_REDIRECT = False
PREPEND_WWW = False
APPEND_SLASH = False

# Mantener configuración de proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Configuraciones de seguridad - COMENTADAS para debugging
# CSRF_COOKIE_SECURE = True      # COMENTADO - permite HTTP
# SESSION_COOKIE_SECURE = True   # COMENTADO - permite HTTP
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# Configuración de archivos multimedia
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50 MB

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'diarioelgobiernoargentina@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'hyyq xjyu nflr mocz')

# ========================================
# LOGGING PARA DEBUGGING CORS (OPCIONAL)
# ========================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'corsheaders': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}