# Generated by Django 5.2 on 2025-09-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='subcategoria_madeinarg',
            field=models.CharField(blank=True, choices=[('calzado', 'Calzado'), ('indumentaria', 'Indumentaria'), ('accesorios', 'Accesorios')], max_length=20, null=True),
        ),
    ]
