# Generated by Django 5.1.1 on 2024-09-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0002_remove_imagen_url_alter_imagen_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen_cabecera_file',
            field=models.ImageField(blank=True, null=True, upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen_cabecera',
            field=models.URLField(blank=True, null=True),
        ),
    ]
