# Generated by Django 5.2 on 2025-09-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0002_alter_contenido_subcategoria_madeinarg'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacioreferencia',
            name='texto_descriptivo',
            field=models.CharField(blank=True, help_text="Texto descriptivo (ej: 'Photographer', 'Fashion Stylist')", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='espacioreferencia',
            name='texto_mostrar',
            field=models.CharField(help_text="Texto que se mostrará como link (ej: 'FFLORENC')", max_length=200),
        ),
    ]
