# Generated by Django 5.2 on 2025-09-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0003_espacioreferencia_texto_descriptivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='rol',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
