# Generated by Django 5.1.1 on 2024-09-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0004_remove_noticia_imagen_cabecera_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='imagen_cabecera',
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen_cabecera_local',
            field=models.ImageField(blank=True, null=True, upload_to='temp_images/'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='magen_cabecera',
            field=models.URLField(blank=True, null=True),
        ),
    ]
