# Generated by Django 5.1.1 on 2024-09-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0005_remove_noticia_imagen_cabecera_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='imagen_cabecera_local',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='magen_cabecera',
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen_cabecera',
            field=models.URLField(default='https://example.com/default-image.jpg'),
        ),
    ]
