# Generated by Django 5.2 on 2025-09-13 13:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0005_alter_contenido_subcategoria_madeinarg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del suscriptor', max_length=100)),
                ('email', models.EmailField(help_text='Email del suscriptor', max_length=254, unique=True)),
                ('fecha_suscripcion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, help_text='Si la suscripción está activa')),
                ('token_desuscripcion', models.UUIDField(default=uuid.uuid4, help_text='Token para desuscribirse', unique=True)),
                ('suscrito_editorials', models.BooleanField(default=True)),
                ('suscrito_issues', models.BooleanField(default=True)),
                ('suscrito_madeinarg', models.BooleanField(default=True)),
                ('suscrito_news', models.BooleanField(default=True)),
                ('suscrito_club_pompa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Suscriptor',
                'verbose_name_plural': 'Suscriptores',
                'ordering': ['-fecha_suscripcion'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('enviado_exitosamente', models.BooleanField(default=False)),
                ('total_enviados', models.PositiveIntegerField(default=0)),
                ('total_errores', models.PositiveIntegerField(default=0)),
                ('log_errores', models.TextField(blank=True, help_text='Log de errores durante el envío', null=True)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='diarioback.contenido')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
