# Generated by Django 5.1.1 on 2024-09-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0006_remove_noticia_imagen_cabecera_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen_1_local',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen_2_local',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen_3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen_3_local',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen_4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen_4_local',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen_5',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen_5_local',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen_6',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen_6_local',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen_local',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
