# Generated by Django 5.1.1 on 2024-09-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0007_noticia_imagen_1_noticia_imagen_1_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='foto_perfil_local',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='foto_perfil',
            field=models.URLField(blank=True, null=True),
        ),
    ]
