# Generated by Django 5.1.1 on 2024-09-09 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0009_remove_trabajador_contraseña_noticia_editor_en_jefe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='editor_en_jefe',
        ),
    ]
