# Generated by Django 5.1.1 on 2024-09-09 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0010_remove_noticia_editor_en_jefe'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='editor_en_jefe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias_supervisadas', to='diarioback.trabajador'),
        ),
    ]
