# Generated by Django 5.1.1 on 2024-09-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0011_noticia_editor_en_jefe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen_cabecera',
            field=models.URLField(blank=True, null=True),
        ),
    ]
