# Generated by Django 5.1.1 on 2024-09-13 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0013_alter_trabajador_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='trabajadores',
            field=models.ManyToManyField(blank=True, related_name='roles', to='diarioback.trabajador'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='contraseña',
            field=models.CharField(default='default_password', max_length=128),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='foto_perfil_local',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trabajadores_asignados', to='diarioback.rol'),
        ),
    ]
