# Generated by Django 5.1.1 on 2024-09-13 02:57

import diarioback.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0014_rol_trabajadores_trabajador_contraseña_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='trabajadores',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='contraseña',
        ),
        migrations.AlterField(
            model_name='rol',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[diarioback.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='foto_perfil_local',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajadores', to='diarioback.rol'),
        ),
    ]
