# Generated by Django 5.1.1 on 2024-09-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0016_noticia_url_alter_noticia_nombre_noticia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
