# Generated by Django 5.1.1 on 2024-09-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0019_noticia_subtitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
