# Generated by Django 5.1.1 on 2024-10-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0020_alter_trabajador_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='seccion',
        ),
        migrations.AddField(
            model_name='noticia',
            name='seccion1',
            field=models.CharField(choices=[('Portada', 'Portada')], default='Portada', max_length=100),
        ),
        migrations.AddField(
            model_name='noticia',
            name='seccion2',
            field=models.CharField(choices=[('Política', 'Política')], default='Política', max_length=100),
        ),
        migrations.AddField(
            model_name='noticia',
            name='seccion3',
            field=models.CharField(choices=[('Economía', 'Economía')], default='Economía', max_length=100),
        ),
        migrations.AddField(
            model_name='noticia',
            name='seccion4',
            field=models.CharField(choices=[('Cultura', 'Cultura')], default='Cultura', max_length=100),
        ),
        migrations.AddField(
            model_name='noticia',
            name='seccion5',
            field=models.CharField(choices=[('Mundo', 'Mundo')], default='Mundo', max_length=100),
        ),
        migrations.AddField(
            model_name='noticia',
            name='seccion6',
            field=models.CharField(choices=[('Deportes', 'Deportes')], default='Deportes', max_length=100),
        ),
    ]
