# Generated by Django 5.1.1 on 2024-10-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0021_remove_noticia_seccion_noticia_seccion1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='seccion1',
            field=models.CharField(blank=True, choices=[('Portada', 'Portada')], default='Portada', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='seccion2',
            field=models.CharField(blank=True, choices=[('Política', 'Política')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='seccion3',
            field=models.CharField(blank=True, choices=[('Economía', 'Economía')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='seccion4',
            field=models.CharField(blank=True, choices=[('Cultura', 'Cultura')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='seccion5',
            field=models.CharField(blank=True, choices=[('Mundo', 'Mundo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='seccion6',
            field=models.CharField(blank=True, choices=[('Deportes', 'Deportes')], max_length=100, null=True),
        ),
    ]
