# Generated by Django 5.1.1 on 2024-10-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0024_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='descripcion_usuario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
