# Generated by Django 5.1.1 on 2024-10-06 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0026_trabajador_descripcion_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='descripcion_usuario',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diarioback.userprofile'),
        ),
    ]
