# Generated by Django 5.1.1 on 2025-01-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0027_remove_trabajador_descripcion_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='seccion4',
            field=models.CharField(blank=True, choices=[('Cultura y sociedad', 'Cultura y sociedad')], max_length=100, null=True),
        ),
    ]
