# Generated by Django 5.1.1 on 2025-01-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0029_newsreaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsreaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('Me_interesa', 'Me_interesa'), ('laugh', 'Laugh'), ('angry', 'Angry'), ('sad', 'Sad')], max_length=22),
        ),
    ]
