# Generated by Django 5.1.1 on 2025-01-13 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0030_alter_newsreaction_reaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsreaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'Me gusta'), ('Me_interesa', 'Me interesa'), ('laugh', 'Me divierte'), ('angry', 'Me enoja'), ('sad', 'Me entristece')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='newsreaction',
            index=models.Index(fields=['news', 'user'], name='diarioback__news_id_2a74bf_idx'),
        ),
        migrations.AddIndex(
            model_name='newsreaction',
            index=models.Index(fields=['reaction_type'], name='diarioback__reactio_55ba37_idx'),
        ),
    ]
