# Generated by Django 5.1.1 on 2025-01-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0031_alter_newsreaction_reaction_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsReaction',
        ),
    ]
