# Generated by Django 5.1.1 on 2025-01-14 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0033_reaccionnoticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticiaViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('contador', models.PositiveIntegerField(default=0)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistas', to='diarioback.noticia')),
            ],
            options={
                'unique_together': {('noticia', 'fecha')},
            },
        ),
    ]
