# Generated by Django 5.1.1 on 2025-01-14 14:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0034_noticiaviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-contador_visitas']},
        ),
        migrations.AddField(
            model_name='noticia',
            name='contador_visitas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='noticia',
            name='ultima_actualizacion_contador',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='NoticiaVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='diarioback.noticia')),
            ],
        ),
        migrations.DeleteModel(
            name='NoticiaViews',
        ),
        migrations.AddIndex(
            model_name='noticiavisita',
            index=models.Index(fields=['fecha'], name='diarioback__fecha_11c71e_idx'),
        ),
        migrations.AddIndex(
            model_name='noticiavisita',
            index=models.Index(fields=['noticia'], name='diarioback__noticia_416b00_idx'),
        ),
    ]
