# Generated by Django 5.1.1 on 2025-01-15 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0035_alter_noticia_options_noticia_contador_visitas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='tags',
            new_name='Palabras_clave',
        ),
    ]
