# Generated by Django 5.1.1 on 2025-01-31 23:55

import diarioback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0040_alter_noticia_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categorias',
            field=models.TextField(blank=True, null=True, validators=[diarioback.models.Noticia.validate_categorias]),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
