# Generated by Django 5.1.1 on 2025-04-04 13:13

import diarioback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0051_alter_noticia_categorias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='imagen_local',
            new_name='imagen_cabecera_local',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categorias',
            field=models.TextField(blank=True, null=True, validators=[diarioback.models.Noticia.validate_categorias]),
        ),
    ]
