# Generated by Django 5.1.1 on 2025-04-04 13:45

import diarioback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0052_rename_imagen_local_noticia_imagen_cabecera_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categorias',
            field=models.TextField(blank=True, null=True, validators=[diarioback.models.Noticia.validate_categorias]),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen_cabecera',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
