# Generated by Django 5.1.1 on 2025-04-04 14:39

import diarioback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0053_alter_noticia_categorias_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='imagen_cabecera_local',
            new_name='imagen_local',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categorias',
            field=models.TextField(blank=True, null=True, validators=[diarioback.models.Noticia.validate_categorias]),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen_cabecera',
            field=models.URLField(blank=True, null=True),
        ),
    ]
