# Generated by Django 5.1.1 on 2025-04-04 20:04

import diarioback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0055_alter_noticia_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='imagen_cabecera',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categorias',
            field=models.TextField(blank=True, null=True, validators=[diarioback.models.Noticia.validate_categorias]),
        ),
    ]
