# Generated by Django 5.1.1 on 2025-04-04 23:41

import diarioback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0056_remove_noticia_imagen_cabecera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='foto_perfil_temp',
            field=models.ImageField(blank=True, null=True, upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categorias',
            field=models.TextField(blank=True, null=True, validators=[diarioback.models.Noticia.validate_categorias]),
        ),
    ]
