# Generated by Django 5.2 on 2025-05-11 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0059_alter_noticia_categorias'),
    ]

    operations = [
    ]
