# Generated by Django 5.2 on 2025-05-16 22:01

import diarioback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0064_alter_noticia_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categorias',
            field=models.TextField(blank=True, null=True, validators=[diarioback.models.Noticia.validate_categorias]),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='nombre_noticia',
            field=models.CharField(max_length=500),
        ),
    ]
