# Generated by Django 5.2 on 2025-05-25 19:49

import diarioback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0066_alter_noticia_categorias_alter_noticia_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='contador_visitas_total',
            field=models.PositiveIntegerField(default=0, help_text='Contador permanente total'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categorias',
            field=models.TextField(blank=True, null=True, validators=[diarioback.models.Noticia.validate_categorias]),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='contador_visitas',
            field=models.PositiveIntegerField(default=0, help_text='Contador semanal que se reinicia'),
        ),
    ]
